# Generated by Django 4.2.13 on 2024-06-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
